### ISSUE TITLE
When i install the npm package on a react app, the components do not get imported

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/demo-ui-library#7]
The components are there. And I can view them in Storybook. But when I import the package locally on my system into a React page or install it from npm, the app doesn't seem to find the components.

**Comment by VishalMyla** [comment]
Can I work on this issue?

**Comment by Timonwa** [comment]
Yes @VishalMyla , you can go ahead to work on it. Thank you. And please give it a star if you can.

**Comment by DavidRGz** [comment]
I managed to resolve the issue by replacing all occurrences of

```jsx
export * from "./components";
```

with

```jsx
import { Button } from "./components";
export { Button };
```

Does this make sense? Also, thanks for the library!

**Comment by Timonwa** [comment]
Hi @DavidRGz, I hope it works. Let me try it out
